package org.example.algorithmdebug.contracts.coordination;

/** Coordinator、操作幂等和结论门禁使用的稳定错误码。 */
public enum CoordinationErrorCode {
    COORDINATION_IDENTITY_MISMATCH,
    COORDINATION_ACTION_NOT_ALLOWED,
    COORDINATION_STATE_INVALID,
    COORDINATION_PREREQUISITE_MISSING,
    COORDINATION_POSTCONDITION_FAILED,
    ACTION_OPERATION_ID_REQUIRED,
    TARGET_EXECUTION_BUSY,
    OPERATION_IN_PROGRESS,
    OPERATION_UNCERTAIN,
    OPERATION_JOURNAL_CONFLICT,
    CONCLUSION_NOT_ELIGIBLE
}
